In [1]:
import pandas as pd
import numpy as np

In [2]:
news_data = pd.read_csv("news/news_significant_results_final_features.csv")
papers_data = pd.read_csv("papers/papers_significant_results_final_features.csv")
reddit_data = pd.read_csv("reddit/reddit_significant_results_final_features.csv")

In [7]:
# for each of the time, ONSET_chatgpt, and POST_chatgpt terms (in the term column), extract the conf.low and conf.high values and put them in a [x, y] format

for dataset, dataset_name in zip(
    [news_data, papers_data, reddit_data], ["news", "papers", "reddit"]
):
    print(dataset_name)
    for term_value in ["time", "ONSET_chatgpt", "POST_chatgpt"]:
        print(term_value)
        term_data = dataset[dataset["term"] == term_value]
        term_data = term_data[["conf.low", "conf.high"]]
        term_data = term_data.to_numpy()
        term_data = np.round(term_data, decimals=4)
        print(term_data)
        print("-----------------")
    print("#################")

news
time
[[0.0001 0.0005]]
-----------------
ONSET_chatgpt
[[-1.8815 -0.9293]]
-----------------
POST_chatgpt
[[-0.0044 -0.    ]]
-----------------
#################
papers
time
[[-0.001  -0.0008]]
-----------------
ONSET_chatgpt
[[-0.2583  0.1729]]
-----------------
POST_chatgpt
[[-0.0019 -0.001 ]]
-----------------
#################
reddit
time
[[-0.0005  0.    ]]
-----------------
ONSET_chatgpt
[[-0.0761  0.9083]]
-----------------
POST_chatgpt
[[-0.0031 -0.0011]]
-----------------
#################
